export function getInitialGrants(adminRoleId, adminUserId) {
  return [
    {
      resource: 'post',
      action: 'create:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'post',
      action: 'read:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'post',
      action: 'update:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'post',
      action: 'delete:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'category',
      action: 'create:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'category',
      action: 'read:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'category',
      action: 'update:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'category',
      action: 'delete:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'user',
      action: 'create:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'user',
      action: 'read:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'user',
      action: 'update:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'user',
      action: 'delete:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'role',
      action: 'create:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'role',
      action: 'read:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'role',
      action: 'update:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'role',
      action: 'delete:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'grant',
      action: 'create:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'grant',
      action: 'read:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'grant',
      action: 'update:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
    {
      resource: 'grant',
      action: 'delete:any',
      attributes: '*',
      roleId: adminRoleId,
      userId: adminUserId,
    },
  ];
}
